[env:s2mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
lib_deps = file://../..
build_flags =
    -DIBXM_STREAMING=0
    -DHC_BCLK=5
    -DHC_WS=6
    -DHC_DATA=7
